#!/bin/sh
#
# @name Dual Axes Tiltrotor X500 V2
#
# @type Tiltrotor Quadrotor x
# @class Copter
#
# @maintainer Ahmad Ziad Zain Aldeen <ahmad.zain@torontomu.ca>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.tm_defaults

param set-default IMU_GYRO_CUTOFF 30

param set-default MC_ROLLRATE_P 0.14
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_I 0.3
param set-default MC_PITCHRATE_I 0.3
param set-default MC_ROLLRATE_D 0.004
param set-default MC_PITCHRATE_D 0.004

param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4

param set-default  CA_ROTOR0_PX   0.355
param set-default  CA_ROTOR0_PY   0.355
param set-default  CA_ROTOR0_PZ   0.0
param set-default  CA_ROTOR0_AX   0.0
param set-default  CA_ROTOR0_AY   0.0
param set-default  CA_ROTOR0_AZ  -1.0
param set-default  CA_ROTOR0_CT   6.50
param set-default  CA_ROTOR0_KM   0.05

param set-default  CA_ROTOR1_PX  -0.355
param set-default  CA_ROTOR1_PY  -0.355
param set-default  CA_ROTOR1_PZ   0.0
param set-default  CA_ROTOR1_AX   0.0
param set-default  CA_ROTOR1_AY   0.0
param set-default  CA_ROTOR1_AZ  -1.0
param set-default  CA_ROTOR1_CT   6.50
param set-default  CA_ROTOR1_KM   0.05

param set-default  CA_ROTOR2_PX   0.355
param set-default  CA_ROTOR2_PY  -0.355
param set-default  CA_ROTOR2_PZ   0.0
param set-default  CA_ROTOR2_AX   0.0
param set-default  CA_ROTOR2_AY   0.0
param set-default  CA_ROTOR2_AZ  -1.0
param set-default  CA_ROTOR2_CT   6.50
param set-default  CA_ROTOR2_KM  -0.05

param set-default  CA_ROTOR3_PX  -0.355
param set-default  CA_ROTOR3_PY   0.355
param set-default  CA_ROTOR3_PZ   0.0
param set-default  CA_ROTOR3_AX   0.0
param set-default  CA_ROTOR3_AY   0.0
param set-default  CA_ROTOR3_AZ  -1.0
param set-default  CA_ROTOR3_CT   6.50
param set-default  CA_ROTOR3_KM  -0.05



########### tiltrotor specific parameters ###########

param set-default CA_NORMALIZED 0

param set-default CA_AIRFRAME 13
param set-default CA_SV_TL_COUNT 8

param set-default CA_SV_TL0_MAXA  60.0000
param set-default CA_SV_TL0_MINA -60.0000
param set-default CA_SV_TL1_MAXA  60.0000
param set-default CA_SV_TL1_MINA -60.0000
param set-default CA_SV_TL2_MAXA  60.0000
param set-default CA_SV_TL2_MINA -60.0000
param set-default CA_SV_TL3_MAXA  60.0000
param set-default CA_SV_TL3_MINA -60.0000
param set-default CA_SV_TL4_MAXA  60.0000
param set-default CA_SV_TL4_MINA -60.0000
param set-default CA_SV_TL5_MAXA  60.0000
param set-default CA_SV_TL5_MINA -60.0000
param set-default CA_SV_TL6_MAXA  60.0000
param set-default CA_SV_TL6_MINA -60.0000
param set-default CA_SV_TL7_MAXA  60.0000
param set-default CA_SV_TL7_MINA -60.0000

param set-default CA_SV_TL0_MAXM  25.0000
param set-default CA_SV_TL0_MINM -25.0000
param set-default CA_SV_TL1_MAXM  25.0000
param set-default CA_SV_TL1_MINM -25.0000
param set-default CA_SV_TL2_MAXM  25.0000
param set-default CA_SV_TL2_MINM -25.0000
param set-default CA_SV_TL3_MAXM  25.0000
param set-default CA_SV_TL3_MINM -25.0000
param set-default CA_SV_TL4_MAXM  25.0000
param set-default CA_SV_TL4_MINM -25.0000
param set-default CA_SV_TL5_MAXM  25.0000
param set-default CA_SV_TL5_MINM -25.0000
param set-default CA_SV_TL6_MAXM  25.0000
param set-default CA_SV_TL6_MINM -25.0000
param set-default CA_SV_TL7_MAXM  25.0000
param set-default CA_SV_TL7_MINM -25.0000

# # OLD
# param set-default CA_SV_TL0_TRM -3.0000
# param set-default CA_SV_TL1_TRM -3.5000
# param set-default CA_SV_TL2_TRM  3.0000
# param set-default CA_SV_TL3_TRM -3.5000

# NEW
param set-default CA_SV_TL0_TRM 0.0000
param set-default CA_SV_TL1_TRM 0.0000
param set-default CA_SV_TL2_TRM 0.0000
param set-default CA_SV_TL3_TRM 0.0000
param set-default CA_SV_TL4_TRM 0.0000
param set-default CA_SV_TL5_TRM 0.0000
param set-default CA_SV_TL6_TRM 0.0000
param set-default CA_SV_TL7_TRM 0.0000

param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 204
param set-default PWM_MAIN_FUNC5 205
param set-default PWM_MAIN_FUNC6 206
param set-default PWM_MAIN_FUNC7 207
param set-default PWM_MAIN_FUNC8 208
param set-default PWM_MAIN_TIM0 50

param set-default PWM_MAIN_DIS1 1600
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_MAIN_DIS3 1500
param set-default PWM_MAIN_DIS4 1300
param set-default PWM_MAIN_DIS5 1500
param set-default PWM_MAIN_DIS6 1300
param set-default PWM_MAIN_DIS7 1600
param set-default PWM_MAIN_DIS8 1500

param set-default PWM_MAIN_MAX1 2100
param set-default PWM_MAIN_MAX2 2000
param set-default PWM_MAIN_MAX3 2000
param set-default PWM_MAIN_MAX4 1800
param set-default PWM_MAIN_MAX5 2000
param set-default PWM_MAIN_MAX6 1800
param set-default PWM_MAIN_MAX7 2100
param set-default PWM_MAIN_MAX8 2000

param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_MAIN_MIN3 1000
param set-default PWM_MAIN_MIN4 800
param set-default PWM_MAIN_MIN5 1000
param set-default PWM_MAIN_MIN6 800
param set-default PWM_MAIN_MIN7 1100
param set-default PWM_MAIN_MIN8 1000

param set-default PWM_MAIN_REV 15

param set-default CA_TM_CUTOFF 0.125
param set-default CA_TM_RU     1
param set-default CA_TM_AXIS 0 # 0 for DUAL , 1 for SINGLE-LATERAL and 2 for SINGLE-BILATERAL


# YAW PID setup

param set-default MC_YAWRATE_P 0.0500
param set-default MC_YAWRATE_I 0.0000
param set-default MC_YAWRATE_D 0.0000
param set-default MC_YAWRATE_K 0.5000

param set-default POS_NO_TILT 1


# battery setup
param set-default BAT_N_CELLS 4
param set-default BAT_V_CHARGED 4.2000
param set-default BAT_V_DIV 18.4482
param set-default BAT_V_EMPTY 4
param set-default BAT_V_LOAD_DROP 0

param set-default BAT1_N_CELLS 4
param set-default BAT1_V_CHARGED 4.2000
param set-default BAT1_V_DIV 18.4482


# radio setup
param set-default COM_FLTMODE1 8
param set-default COM_FLTMODE4 7
param set-default COM_FLTMODE6 11
param set-default MAN_ARM_GESTURE 0


# offboard mode with xrce
param set-default EKF2_HGT_REF 3
param set-default UXRCE_DDS_CFG 102
param set-default SER_TEL2_BAUD 921600
param set-default EKF2_EV_CTRL 7
param set-default SDLOG_MODE 2
